// 组件库按需引入
import {
    Button,
    Cell,
    Icon,
    Image as VanImage,
    Popup,
    Toast,
    Calendar,
    Cascader,
    Checkbox, CheckboxGroup,
    DatePicker,
    Field, CellGroup,
    Form,
    NumberKeyboard,
    PasswordInput,
    Picker,
    RadioGroup, Radio,
    Rate,
    Search,
    Slider,
    Stepper,
    Switch,
    TimePicker,
    Uploader,
    ActionSheet,
    Dialog,
    DropdownMenu, DropdownItem,
    Loading,
    Notify,
    Overlay,
    PullRefresh,
    ShareSheet,
    SwipeCell,
    Badge,
    Circle,
    Collapse, CollapseItem,
    CountDown,
    Empty,
    ImagePreview,
    List,
    NoticeBar,
    Popover,
    Progress,
    Skeleton,
    Sticky,
    Swipe, SwipeItem,
    Tag,
    Pagination,
    Tab, Tabs,
    TreeSelect,

} from 'vant';

const components = [
    Button,
    Cell,
    Icon,
    VanImage,
    Popup,
    Toast,
    Calendar,
    Cascader,
    Checkbox, CheckboxGroup,
    DatePicker,
    Field, CellGroup,
    Form,
    NumberKeyboard,
    PasswordInput,
    Picker,
    RadioGroup, Radio,
    Rate,
    Search,
    Slider,
    Stepper,
    Switch,
    TimePicker,
    Uploader,
    ActionSheet,
    Dialog,
    DropdownMenu, DropdownItem,
    Loading,
    Notify,
    Overlay,
    PullRefresh,
    ShareSheet,
    SwipeCell,
    Badge,
    Circle,
    Collapse, CollapseItem,
    CountDown,
    Empty,
    ImagePreview,
    List,
    NoticeBar,
    Popover,
    Progress,
    Skeleton,
    Sticky,
    Swipe, SwipeItem,
    Tag,
    Pagination,
    Tab, Tabs,
    TreeSelect,
]

// 加载全局样式
import '@/core/assets/global.css';

// 预安装插件
export default {
    install: function (app, opts = {}) {
        // 安装UI
        components.forEach(component => {
            app.use(component);
        });

    }
}